name: Generate snake animation

on:
  schedule:
    - cron: "* */12 * * *" # Isso fará o fluxo rodar a cada 12 horas
  workflow_dispatch:  # Permite executar manualmente se necessário
  push:
    branches:
      - master  # Quando você fizer push na branch principal (master)

jobs:
  generate:
    runs-on: ubuntu-latest  # Executa em um ambiente Ubuntu

    steps:
      - name: Gerar a animação da cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Subir a animação para o GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Usará a branch output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
